# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97ea5188d3be861e265d94781338eafc95347ce97bd226404a94791d5b79a301cc01854d7717a8717f966cb0f484b1e8f5275adb79214e74dbb3b9f7a4a33698

test:
  secret_key_base: 242ee346354484a6c13d74f1eeba46d15b113a9a4ab83b3bb5bcd3f7dba6e56d8083cfcc9b0560d0bd9952b91faf1a8859fb7f691ff086955db55de0a935b6df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
